### ISSUE TITLE
No support of ajax url changing.

### ISSUE THREAD

**Issue by pdglobal** [derp-all-day/JSBot#3] opened 2020-01-13 18:55 UTC
I have this all installed and working now on my website.

However I have noticed the "portal" only updates on a full reload of the webpage.

It seems to ignore changes to the url by javascript.

Would it be necessary to add some code into my javascript ajax functions, or could this be resolved on your end?

**Comment by pdglobal** [comment] 2020-01-13 19:02
I don't know if this is related, but eventually, my panels shows that I am offline even when I'm still on my site and requests are still being made to the backend,

**Comment by derp-all-day** [comment] 2020-01-13 19:04
It should, however I am unsure if document.location.href registers these changes to the url (Thats what it calls to get the current url from when it sends it over).

This is done every 60 seconds when it calls "portal.php?post=hello"

I am at work, so it's kind of hard for me to look into this at the moment.

However if you wanted to give it a look, the 'hello' function in listener.php at line 94 is where this bit of code resides.

**Comment by derp-all-day** [comment] 2020-01-13 19:07
And as far as your second question, theres this but of code here from the 'listener.php' in the image I attached. This code pauses the server when the window is not in view and unpauses when it is. This is to protect from say if the same user have 3 tabs of different pages of the site open to make sure commands only get sent to the active one. If that makes sense.

![Untitled](https://user-images.githubusercontent.com/17708635/72284053-b2c1c080-3605-11ea-9785-9bcedde8124f.png)

**Comment by derp-all-day** [comment] 2020-01-13 19:13
If you wish to cancel out this functionality, just comment out/or remove the lines 27-31 in that file although be warned, will result in unexpected behavior if users have multiple tabs of your site open.

**Comment by pdglobal** [comment] 2020-01-13 19:19
![image](https://user-images.githubusercontent.com/36902779/72284652-86ab3d00-360f-11ea-94e9-256b752885ea.png)
I modified your source code to use a variable set by my ajax function as the referrer. I also added a call to the hello function in my ajax function.

**Comment by derp-all-day** [comment] 2020-01-13 19:20
Not a bad solution actually

**Comment by derp-all-day** [comment] 2020-01-13 19:23
Also I would redact your screenshot of that's your home connection unless you care about leaking your IP. :)

**Comment by derp-all-day** [comment] 2020-01-13 19:28
In the future I will add an event listenerto catch any url changes made by Ajax though. Thankyou for bringing that to my attention. Anything else I can help you with?

**Comment by pdglobal** [comment] 2020-01-13 19:30
How do I make the control panel update faster? Where's the code that defines the poll rate?

**Comment by derp-all-day** [comment] 2020-01-13 19:35
From listeners.php, lines 37 and 37 under the start() function (as displayed in attached image) define the interval rate at 30 seconds and 60 seconds respectivly. You can modify those values there. Although be careful setting them too short if you have any concerns about bandwidth. (will be updating the source to use websockets in the future which will solve this issue and allow everything to be more real-time, but as for now stuck with long-polling)

![image](https://user-images.githubusercontent.com/17708635/72285673-36c97780-3609-11ea-9b25-b0f54d33d342.png)

**Comment by pdglobal** [comment] 2020-01-13 19:38
Sorry but now I've run into another error.

![image](https://user-images.githubusercontent.com/36902779/72286052-59ac5980-3612-11ea-813f-4d9bcd03a88d.png)

**Comment by pdglobal** [comment] 2020-01-13 19:39
When data is sent to the hello handler.

**Comment by derp-all-day** [comment] 2020-01-13 19:41
can you share with me:
1. what you set the interval rate to for hello()
2. any changes you made to the hello function (Give me a screenshot of the entire function with changes you made)

**Comment by pdglobal** [comment] 2020-01-13 19:43
The interval rate for hello is set to 30 second and whenever a new page is loaded

![image](https://user-images.githubusercontent.com/36902779/72286351-fa027e00-3612-11ea-956d-06611f87d684.png)

![image](https://user-images.githubusercontent.com/36902779/72286377-0d154e00-3613-11ea-9154-192c8a83af17.png)

**Comment by pdglobal** [comment] 2020-01-13 19:45
![image](https://user-images.githubusercontent.com/36902779/72286532-52d21680-3613-11ea-851d-06e30aff2f6f.png)

**Comment by derp-all-day** [comment] 2020-01-13 19:55
hmm, did you make any changes to portal.php?

**Comment by derp-all-day** [comment] 2020-01-13 19:58
Oh, your "currentPage" variable is defined out of scope, so it's not registering in inside the function. pretty sure thats whats going on. Give me 5 mins to get back to my desk and I'll try and drum up a working solution for you.

**Comment by derp-all-day** [comment] 2020-01-13 20:14
Okay, First, add this declaration inside the jr object (Id say add right after line 22, and remove the variable declaration you made at the start of the file.
``currentPage: "/?pid=index",``

Next, change the POST data in the hello function to this to reflect our object variable:
``{ref: jsr.currentPage}``

And last, you can set this before calling hello at any point simply by doing this:
``jsr.currentPage = "something"``

That should work for you, let me know

**Comment by derp-all-day** [comment] 2020-01-13 20:23
Oh! In your request I see whats wrong, you may not need to do what I wrote up

**Comment by derp-all-day** [comment] 2020-01-13 20:24
Change:
'referer' in line 3224 of your code, to 'ref'

The variable that portal.php looks for in the post data is 'ref'.

**Comment by derp-all-day** [comment] 2020-01-13 20:25
Ive redacted my previous answer so as not to potencially lead you down the wrong rabbit hole.

**Comment by derp-all-day** [comment] 2020-01-13 20:29
Likewise, you could also just set the variable, and call jsr.hello(); itself rather than manually re-crafting the request. However, either should be fine.

**Comment by derp-all-day** [comment] 2020-01-13 20:34
Also, after fixing that, you may want to delete your test connection and let it re-populate itself because this may have caused issues with it's db entry.

**Comment by pdglobal** [comment] 2020-01-13 20:39
Thanks, I got it all working again.

**Comment by pdglobal** [comment] 2020-01-13 20:41
Also, something I didn't point out, I want the control panel to update faster, I already found out how to speed up the automated requests sent by the client.

**Comment by derp-all-day** [comment] 2020-01-13 20:41
Awesome! Glad to hear it :)

**Comment by derp-all-day** [comment] 2020-01-13 20:43
That can be changed in line 92 (last line I believe) of the /js/ajax.js file.

**Comment by pdglobal** [comment] 2020-01-13 20:45
perfect! Thanks for all your help. I'll be following this project to see what all you add to it

**Closed** 2020-01-13 20:46 UTC
