### ISSUE TITLE
Database corruption error

### ISSUE THREAD

**Issue by pdglobal** [derp-all-day/JSBot#5] opened 2020-01-13 21:34 UTC
This has happened to me twice now, the first time required a reinstall.

After running this for a while slaves.php starts to throw this error:

PHP Warning:  Invalid argument supplied for foreach() in C:\PDGLOBAL.NET\htdocs\admin\classes\phdtools.class.php on line 552
PHP Fatal error:  Uncaught Exception: get(): column 'lastSeen'@'slaves' does not exist. in C:\PDGLOBAL.NET\htdocs\admin\classes\phd.class.php:301
Stack trace:
#0 C:\PDGLOBAL.NET\htdocs\admin\classes\phd.class.php(413): PHD->order_output(Array)
#1 C:\PDGLOBAL.NET\htdocs\admin\ajax\slaves.php(11): PHD->get()
#2 {main}
  thrown in C:\PDGLOBAL.NET\htdocs\admin\classes\phd.class.php on line 301

**Comment by derp-all-day** [comment] 2020-01-13 21:37
add this to your index.php file right after the ``include 'sys/head.php' near the top. Run once to recreate the table. and then remove the lines.
```
$db->table('slaves')->delete();
$db->table('slaves', array(
  'ip'          => 'string',
  'lastSeen'    => 'string',
  'firstSeen'   => 'string',
  'ua'          => 'string',
  'os'          => 'string',
  'uuid'        => 'string',
  'page'        => 'string',
  'keylog'      => 'string'
))->create();
die();
```

**Comment by pdglobal** [comment] 2020-01-13 21:39
But this has happened more than once? What's the ultimate solution?

**Comment by derp-all-day** [comment] 2020-01-13 21:58
I would say that its most likely a result of all the changes we've been making here with your souce and bad calls being made in the process.

Wait and see, I see no reason why it should be doing that otherwise. My bet is that it wont happen again.

**Comment by pdglobal** [comment] 2020-01-13 22:04
It's happened twice more. I've decreased the rate at which the slaves page is requested, in case overlapping attempts to access the database are somehow causing this to happen. Didn't start happening until I messed with that.

**Comment by derp-all-day** [comment] 2020-01-13 22:14
Yeah that's another possibility, although it shouldn't be because PHD should be requesting file lock before update. I'll look into that once I get home this evening. Leave this issue open untill then and il get back to you on what I find. Untill then, I think you have the right idea

**Comment by pdglobal** [comment] 2020-01-13 22:37
Seems to be the case. I've increased the delay from 1000ms to 2500ms and I havent experienced this again.

**Comment by derp-all-day** [comment] 2020-01-13 22:42
Oooo yeah. That's an awefully short poll time.

**Comment by pdglobal** [comment] 2020-01-13 22:47
This worries me though. Imagine there's a peroid of high user traffic on my server where the listener pages are receiving more than one request every second. Wouldn't that also have a high probability of causing this same issue?

**Comment by derp-all-day** [comment] 2020-01-14 01:45
Mmm, thats one of the reasons I have the poll time set so short. However PHD is also a work of mine. This should be fixed through file locking, the solution may also be to have php set a que if the file is locked. Id set your time to atleast 5 seconds and I'll work on a solution to that. at 30 seconds I was able to handle 300 concurrent connections. Almost wonder if it may be a difference in how IIS handles i/o file access. But I'll look into it.

**Comment by derp-all-day** [comment] 2020-01-14 06:28
Im going to close this for now. I'm unable to reproduce the issue, however I will look into what I stated above, it will just take some time. I'll re-open this issue once theres an update to alert you.

**Comment by pdglobal** [comment] 2020-01-14 23:44
Okay it must be either FastCGI or IIS related, because this has happened twice more today when I wasn't even polling the control panel.

**Comment by derp-all-day** [comment] 2020-01-15 00:08
Hmmm, I'll see it I cant drum up a vm with iis and see if I cant reproduce and figgure out why because I would like for it to work on iis aswell.

**Comment by derp-all-day** [comment] 2020-01-15 00:20
Actually one thing you can do for me. Reproduce the error, and when it happens, grab the contents of the file located at:
``/{DBFolder}/{DBUser}/slaves/table.tb``

and send me the contents (Thats the file thats claiming to have been corrupted).

That could actually help a great deal in figuring out why it's doing this.

**Comment by pdglobal** [comment] 2020-01-15 02:18
"null"

![image](https://user-images.githubusercontent.com/36902779/72399189-649ae300-3713-11ea-9709-066f621b722a.png)

**Comment by derp-all-day** [comment] 2020-01-15 02:20
Huh, well that's deffinitly not right at all and also a first for me seeing that. PHD uses JSON for it's storage, I'll have see if I cant replicate this myself. That's really strange.

**Comment by derp-all-day** [comment] 2020-01-15 02:23
What do you have your panel refresh rate set at? (under the possibility it still may have to do with file locking problems) as each time that refresh is called, it's querying that table

**Comment by pdglobal** [comment] 2020-01-15 02:37
My panel refresh delay is 2.5 seconds, however, the panel wasn't open. I came back later in the day to find it broken like this, without the page to the panel even having been open while I was away.

**Comment by pdglobal** [comment] 2020-01-15 02:39
I just reduced the poll rate to once every 5 seconds, but I doubt this was the direct cause because while it did take longer to happen than with the panel open, it did eventually happen even with the panel not polling

**Comment by derp-all-day** [comment] 2020-01-15 02:43
Hmmm if nothing was running then this is extremely weird. And may be just as hard for me to reproduce I fear. If you would like to be able to thoroughly troubleshoot this, would you mind if we added each other on discord if you have one? If I could work 1 on 1 with you it would definitely help speed up figuring out what exactly is going on.

**Comment by pdglobal** [comment] 2020-01-15 02:47
My discord is PDGLOBAL#7597

**Comment by derp-all-day** [comment] 2020-01-15 02:51
Adding you, one second

**Comment by derp-all-day** [comment] 2020-01-15 02:52
Added

**Closed** 2020-01-15 05:49 UTC
